# Generated by YCM Generator at 2017-03-19 12:07:08.462801

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c++',
    '-DFLANN_EXPORTS',
    '-DFLANN_STATIC',
    '-DFLANN_USE_CUDA',
    '-DGTEST_HAS_PTHREAD=1',
    '-DGTEST_TESTING_OUTPUT_DIRECTORY="/tmp/tmp961RiE/testing_output"',
    '-DGTEST_USE_OWN_TR1_TUPLE=1',
    '-DNDEBUG',
    '-DSTATX_WITH_CERES',
    '-DTHEIA_DATA_DIR="/home/lijiang/codes/TheiaSfM/data"',
    '-DTHEIA_GFLAGS_NAMESPACE=google',
    '-DTHEIA_HAS_THREAD_LOCAL_KEYWORD',
    '-DTHEIA_SUITESPARSE_VERSION="4.5.3"',
    '-D_FLANN_VERSION=1.8.4',
    '-I/home/lijiang/codes/TheiaSfM',
    '-I/home/lijiang/codes/TheiaSfM/include',
    '-I/home/lijiang/codes/TheiaSfM/libraries',
    '-I/home/lijiang/codes/TheiaSfM/libraries/akaze',
    '-I/home/lijiang/codes/TheiaSfM/libraries/akaze/.',
    '-I/home/lijiang/codes/TheiaSfM/libraries/cereal',
    '-I/home/lijiang/codes/TheiaSfM/libraries/cereal/include',
    '-I/home/lijiang/codes/TheiaSfM/libraries/flann',
    '-I/home/lijiang/codes/TheiaSfM/libraries/flann/src/cpp',
    '-I/home/lijiang/codes/TheiaSfM/libraries/gtest',
    '-I/home/lijiang/codes/TheiaSfM/libraries/gtest/include',
    '-I/home/lijiang/codes/TheiaSfM/libraries/optimo',
    '-I/home/lijiang/codes/TheiaSfM/libraries/spectra',
    '-I/home/lijiang/codes/TheiaSfM/libraries/statx',
    '-I/home/lijiang/codes/TheiaSfM/libraries/statx/libraries/burkardt_spec_funcs',
    '-I/home/lijiang/codes/TheiaSfM/libraries/stlplus3',
    '-I/home/lijiang/codes/TheiaSfM/libraries/stlplus3/.',
    '-I/home/lijiang/codes/TheiaSfM/libraries/visual_sfm',
    '-I/home/lijiang/codes/TheiaSfM/libraries/visual_sfm/.',
    '-I/home/lijiang/codes/TheiaSfM/libraries/vlfeat',
    '-I/home/lijiang/codes/TheiaSfM/src',
    '-I/usr/include/suitesparse',
    '-I/usr/local',
    '-I/usr/local/include',
    '-Wall',
    '-Wno-deprecated-declarations',
    '-Wno-missing-field-initializers',
    '-Wno-return-type-c-linkage',
    '-Wno-sign-compare',
    '-Wno-unknown-pragmas',
    '-Wno-unused-function',
    '-Wno-unused-parameter',
    '-Wno-unused-result',
    '-inline-threshold=600',
    '-std=c++11',
    '-isystem', '/usr/include/eigen3',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = '/home/lijiang/codes/TheiaSfM/build'

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.H', '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

